import = ["/Users/serdar/.config/alacritty/alacritty-gruvbox-dark.toml"]

live_config_reload=true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "Cousine"

[font]
size = 14.0

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 130
lines = 45

[window.padding]
x = 10
y = 10